### ISSUE TITLE
project folder does not work

### ISSUE THREAD

**Issue by ycrao** [lmatt-bit/atom_open_in_cmd#1]
When I add project folder to the atom, It does not work for me.
![image](https://cloud.githubusercontent.com/assets/3280204/9843974/e70d4f42-5af1-11e5-9738-405b38463ab4.png) 

The path in cmd window does not seem to be right.

**Comment by lmatt-bit** [comment]
Thanks for reporting it. I am investigating now.

**Comment by lmatt-bit** [comment]
@ycrao i can't repo it. can you specify more details how it happen? Thanks.

**Comment by ycrao** [comment]
It become normal, maybe some other cause these!
