### ISSUE TITLE
any project/dir use the same cmd dir

### ISSUE THREAD

**Issue by zwfy1** [lmatt-bit/atom_open_in_cmd#2]
My python script is put in d:\python,but every time I use the "run-command" open the cmd in path "C:\Users\xxx\AppData\Local\atom\app-1.2.0>"

**Comment by lmatt-bit** [comment]
@zwfy1 That issue happens randomly. You can try to re-open the atom editor.

**Comment by jlongo** [comment]
Hi

I have installed the zip version of Atom in F:\Recursos\Atom. Also, i instaled your package. When i click on the corresponding menu from your package, neither in any folder/file on file tree tab or on editor content it always open the cmd window on "F:\Recursos\Atom". I tried reopen Atom with same result. For reference, i use windows 10.

Regards

JL

**Comment by jazzzz** [comment]
I fixed this in PR #3
